namespace OnaySistemi
{
    partial class FrmAnaMenu
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblKullaniciBilgi = new System.Windows.Forms.Label();
            this.lblLogo = new System.Windows.Forms.Label();
            this.pnlSidebar = new System.Windows.Forms.Panel();
            this.btnCikis = new System.Windows.Forms.Button();
            this.btnAdminPanel = new System.Windows.Forms.Button();
            this.btnSifreDeðiþtir = new System.Windows.Forms.Button();
            this.btnRevizeTamamlama = new System.Windows.Forms.Button();
            this.btnBelgeListesi = new System.Windows.Forms.Button();
            this.btnOnayEkrani = new System.Windows.Forms.Button();
            this.btnBelgeGonderim = new System.Windows.Forms.Button();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.lblOzetAciklama = new System.Windows.Forms.Label();
            this.pnlOzetKart = new System.Windows.Forms.Panel();
            this.lblRolDeger = new System.Windows.Forms.Label();
            this.lblRolText = new System.Windows.Forms.Label();
            this.lblBugunDeger = new System.Windows.Forms.Label();
            this.lblBugunText = new System.Windows.Forms.Label();
            this.lblBekleyenDeger = new System.Windows.Forms.Label();
            this.lblBekleyenText = new System.Windows.Forms.Label();
            this.lblOzetBaslik = new System.Windows.Forms.Label();
            this.pnlHeader.SuspendLayout();
            this.pnlSidebar.SuspendLayout();
            this.pnlContent.SuspendLayout();
            this.pnlOzetKart.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.pnlHeader.Controls.Add(this.lblKullaniciBilgi);
            this.pnlHeader.Controls.Add(this.lblLogo);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(900, 60);
            this.pnlHeader.TabIndex = 0;
            this.lblKullaniciBilgi.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblKullaniciBilgi.AutoSize = true;
            this.lblKullaniciBilgi.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblKullaniciBilgi.ForeColor = System.Drawing.Color.White;
            this.lblKullaniciBilgi.Location = new System.Drawing.Point(620, 21);
            this.lblKullaniciBilgi.Name = "lblKullaniciBilgi";
            this.lblKullaniciBilgi.Size = new System.Drawing.Size(127, 20);
            this.lblKullaniciBilgi.TabIndex = 1;
            this.lblKullaniciBilgi.Text = "Kullanýcý: (bilgi yok)";
            this.lblLogo.AutoSize = true;
            this.lblLogo.Font = new System.Drawing.Font("Segoe UI Semibold", 14F, System.Drawing.FontStyle.Bold);
            this.lblLogo.ForeColor = System.Drawing.Color.White;
            this.lblLogo.Location = new System.Drawing.Point(20, 16);
            this.lblLogo.Name = "lblLogo";
            this.lblLogo.Size = new System.Drawing.Size(145, 32);
            this.lblLogo.TabIndex = 0;
            this.lblLogo.Text = "DDOS";
            this.pnlSidebar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.pnlSidebar.Controls.Add(this.btnCikis);
            this.pnlSidebar.Controls.Add(this.btnAdminPanel);
            this.pnlSidebar.Controls.Add(this.btnSifreDeðiþtir);
            this.pnlSidebar.Controls.Add(this.btnRevizeTamamlama);
            this.pnlSidebar.Controls.Add(this.btnBelgeListesi);
            this.pnlSidebar.Controls.Add(this.btnOnayEkrani);
            this.pnlSidebar.Controls.Add(this.btnBelgeGonderim);
            this.pnlSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlSidebar.Location = new System.Drawing.Point(0, 60);
            this.pnlSidebar.Name = "pnlSidebar";
            this.pnlSidebar.Size = new System.Drawing.Size(200, 440);
            this.pnlSidebar.TabIndex = 1;
            this.btnCikis.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCikis.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCikis.Location = new System.Drawing.Point(20, 345);
            this.btnCikis.Name = "btnCikis";
            this.btnCikis.Size = new System.Drawing.Size(160, 35);
            this.btnCikis.TabIndex = 6;
            this.btnCikis.Text = "Çýkýþ";
            this.btnCikis.UseVisualStyleBackColor = true;
            this.btnCikis.Click += new System.EventHandler(this.btnCikis_Click);
            this.btnAdminPanel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdminPanel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAdminPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(100)))), ((int)(((byte)(20)))));
            this.btnAdminPanel.ForeColor = System.Drawing.Color.White;
            this.btnAdminPanel.Location = new System.Drawing.Point(20, 300);
            this.btnAdminPanel.Name = "btnAdminPanel";
            this.btnAdminPanel.Size = new System.Drawing.Size(160, 35);
            this.btnAdminPanel.TabIndex = 5;
            this.btnAdminPanel.Text = "Admin Paneli";
            this.btnAdminPanel.UseVisualStyleBackColor = false;
            this.btnAdminPanel.Click += new System.EventHandler(this.btnAdminPanel_Click);
            this.btnSifreDeðiþtir.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSifreDeðiþtir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSifreDeðiþtir.Location = new System.Drawing.Point(20, 255);
            this.btnSifreDeðiþtir.Name = "btnSifreDeðiþtir";
            this.btnSifreDeðiþtir.Size = new System.Drawing.Size(160, 35);
            this.btnSifreDeðiþtir.TabIndex = 4;
            this.btnSifreDeðiþtir.Text = "Þifre Deðiþtir";
            this.btnSifreDeðiþtir.UseVisualStyleBackColor = true;
            this.btnSifreDeðiþtir.Click += new System.EventHandler(this.btnSifreDeðiþtir_Click);
            this.btnRevizeTamamlama.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRevizeTamamlama.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRevizeTamamlama.Location = new System.Drawing.Point(20, 200);
            this.btnRevizeTamamlama.Name = "btnRevizeTamamlama";
            this.btnRevizeTamamlama.Size = new System.Drawing.Size(160, 35);
            this.btnRevizeTamamlama.TabIndex = 3;
            this.btnRevizeTamamlama.Text = "Revize Tamamlama";
            this.btnRevizeTamamlama.UseVisualStyleBackColor = true;
            this.btnRevizeTamamlama.Click += new System.EventHandler(this.btnRevizeTamamlama_Click);
            this.btnBelgeListesi.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBelgeListesi.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBelgeListesi.Location = new System.Drawing.Point(20, 140);
            this.btnBelgeListesi.Name = "btnBelgeListesi";
            this.btnBelgeListesi.Size = new System.Drawing.Size(160, 35);
            this.btnBelgeListesi.TabIndex = 2;
            this.btnBelgeListesi.Text = "Belge Listesi";
            this.btnBelgeListesi.UseVisualStyleBackColor = true;
            this.btnBelgeListesi.Click += new System.EventHandler(this.btnBelgeListesi_Click);
            this.btnOnayEkrani.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnOnayEkrani.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnOnayEkrani.Location = new System.Drawing.Point(20, 80);
            this.btnOnayEkrani.Name = "btnOnayEkrani";
            this.btnOnayEkrani.Size = new System.Drawing.Size(160, 35);
            this.btnOnayEkrani.TabIndex = 1;
            this.btnOnayEkrani.Text = "Onay Ekraný";
            this.btnOnayEkrani.UseVisualStyleBackColor = true;
            this.btnOnayEkrani.Click += new System.EventHandler(this.btnOnayEkrani_Click);
            this.btnBelgeGonderim.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBelgeGonderim.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBelgeGonderim.Location = new System.Drawing.Point(20, 20);
            this.btnBelgeGonderim.Name = "btnBelgeGonderim";
            this.btnBelgeGonderim.Size = new System.Drawing.Size(160, 35);
            this.btnBelgeGonderim.TabIndex = 0;
            this.btnBelgeGonderim.Text = "Belge Gönderimi";
            this.btnBelgeGonderim.UseVisualStyleBackColor = true;
            this.btnBelgeGonderim.Click += new System.EventHandler(this.btnBelgeGonderim_Click);
            this.pnlContent.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pnlContent.Controls.Add(this.lblOzetAciklama);
            this.pnlContent.Controls.Add(this.pnlOzetKart);
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(200, 60);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Padding = new System.Windows.Forms.Padding(20);
            this.pnlContent.Size = new System.Drawing.Size(700, 440);
            this.pnlContent.TabIndex = 2;
            this.lblOzetAciklama.AutoSize = true;
            this.lblOzetAciklama.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblOzetAciklama.ForeColor = System.Drawing.Color.DimGray;
            this.lblOzetAciklama.Location = new System.Drawing.Point(24, 210);
            this.lblOzetAciklama.Name = "lblOzetAciklama";
            this.lblOzetAciklama.Size = new System.Drawing.Size(359, 20);
            this.lblOzetAciklama.TabIndex = 1;
            this.lblOzetAciklama.Text = "Bu ekran üzerinden tüm iþlemlerinize eriþebilirsiniz.";
            this.pnlOzetKart.BackColor = System.Drawing.Color.White;
            this.pnlOzetKart.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlOzetKart.Controls.Add(this.lblRolDeger);
            this.pnlOzetKart.Controls.Add(this.lblRolText);
            this.pnlOzetKart.Controls.Add(this.lblBugunDeger);
            this.pnlOzetKart.Controls.Add(this.lblBugunText);
            this.pnlOzetKart.Controls.Add(this.lblBekleyenDeger);
            this.pnlOzetKart.Controls.Add(this.lblBekleyenText);
            this.pnlOzetKart.Controls.Add(this.lblOzetBaslik);
            this.pnlOzetKart.Location = new System.Drawing.Point(24, 24);
            this.pnlOzetKart.Name = "pnlOzetKart";
            this.pnlOzetKart.Size = new System.Drawing.Size(500, 180);
            this.pnlOzetKart.TabIndex = 0;
            this.lblRolDeger.AutoSize = true;
            this.lblRolDeger.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.lblRolDeger.ForeColor = System.Drawing.Color.Black;
            this.lblRolDeger.Location = new System.Drawing.Point(170, 120);
            this.lblRolDeger.Name = "lblRolDeger";
            this.lblRolDeger.Size = new System.Drawing.Size(16, 23);
            this.lblRolDeger.TabIndex = 6;
            this.lblRolDeger.Text = "-";
            this.lblRolText.AutoSize = true;
            this.lblRolText.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblRolText.Location = new System.Drawing.Point(15, 120);
            this.lblRolText.Name = "lblRolText";
            this.lblRolText.Size = new System.Drawing.Size(103, 23);
            this.lblRolText.TabIndex = 5;
            this.lblRolText.Text = "Kullanýcý rolü:";
            this.lblBugunDeger.AutoSize = true;
            this.lblBugunDeger.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.lblBugunDeger.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.lblBugunDeger.Location = new System.Drawing.Point(250, 78);
            this.lblBugunDeger.Name = "lblBugunDeger";
            this.lblBugunDeger.Size = new System.Drawing.Size(31, 37);
            this.lblBugunDeger.TabIndex = 4;
            this.lblBugunDeger.Text = "0";
            this.lblBugunText.AutoSize = false;
            this.lblBugunText.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblBugunText.Location = new System.Drawing.Point(15, 88);
            this.lblBugunText.Name = "lblBugunText";
            this.lblBugunText.Size = new System.Drawing.Size(300, 23);
            this.lblBugunText.TabIndex = 3;
            this.lblBugunText.Text = "Bugün gönderilen:";
            this.lblBekleyenDeger.AutoSize = true;
            this.lblBekleyenDeger.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.lblBekleyenDeger.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.lblBekleyenDeger.Location = new System.Drawing.Point(250, 42);
            this.lblBekleyenDeger.Name = "lblBekleyenDeger";
            this.lblBekleyenDeger.Size = new System.Drawing.Size(31, 37);
            this.lblBekleyenDeger.TabIndex = 2;
            this.lblBekleyenDeger.Text = "0";
            this.lblBekleyenText.AutoSize = false;
            this.lblBekleyenText.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblBekleyenText.Location = new System.Drawing.Point(15, 52);
            this.lblBekleyenText.Name = "lblBekleyenText";
            this.lblBekleyenText.Size = new System.Drawing.Size(300, 23);
            this.lblBekleyenText.TabIndex = 1;
            this.lblBekleyenText.Text = "Bekleyen onay sayýsý:";
            this.lblOzetBaslik.AutoSize = true;
            this.lblOzetBaslik.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            this.lblOzetBaslik.Location = new System.Drawing.Point(14, 13);
            this.lblOzetBaslik.Name = "lblOzetBaslik";
            this.lblOzetBaslik.Size = new System.Drawing.Size(104, 25);
            this.lblOzetBaslik.TabIndex = 0;
            this.lblOzetBaslik.Text = "Genel Özet";
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(900, 500);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.pnlSidebar);
            this.Controls.Add(this.pnlHeader);
            this.MinimumSize = new System.Drawing.Size(900, 500);
            this.Name = "FrmAnaMenu";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "DDOS - Ana Menü";
            this.Load += new System.EventHandler(this.FrmAnaMenu_Load);
            this.pnlHeader.ResumeLayout(false);
            this.pnlHeader.PerformLayout();
            this.pnlSidebar.ResumeLayout(false);
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            this.pnlOzetKart.ResumeLayout(false);
            this.pnlOzetKart.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblKullaniciBilgi;
        private System.Windows.Forms.Label lblLogo;
        private System.Windows.Forms.Panel pnlSidebar;
        private System.Windows.Forms.Button btnBelgeGonderim;
        private System.Windows.Forms.Button btnOnayEkrani;
        private System.Windows.Forms.Button btnBelgeListesi;
        private System.Windows.Forms.Button btnRevizeTamamlama;
        private System.Windows.Forms.Button btnSifreDeðiþtir;
        private System.Windows.Forms.Button btnAdminPanel;
        private System.Windows.Forms.Button btnCikis;
        private System.Windows.Forms.Panel pnlContent;
        private System.Windows.Forms.Panel pnlOzetKart;
        private System.Windows.Forms.Label lblOzetBaslik;
        private System.Windows.Forms.Label lblBekleyenText;
        private System.Windows.Forms.Label lblBekleyenDeger;
        private System.Windows.Forms.Label lblBugunDeger;
        private System.Windows.Forms.Label lblBugunText;
        private System.Windows.Forms.Label lblRolDeger;
        private System.Windows.Forms.Label lblRolText;
        private System.Windows.Forms.Label lblOzetAciklama;
    }
}
