namespace OnaySistemi
{
    partial class FrmOnayEkrani
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblBaslik = new System.Windows.Forms.Label();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.pnlAlt = new System.Windows.Forms.Panel();
            this.lblRevizeAciklama = new System.Windows.Forms.Label();
            this.txtRevizeAciklama = new System.Windows.Forms.TextBox();
            this.btnRevizeTalep = new System.Windows.Forms.Button();
            this.btnReddet = new System.Windows.Forms.Button();
            this.btnOnayla = new System.Windows.Forms.Button();
            this.btnYenile = new System.Windows.Forms.Button();
            this.pnlOrta = new System.Windows.Forms.Panel();
            this.pnlDetay = new System.Windows.Forms.Panel();
            this.lblDosyaDeger = new System.Windows.Forms.Label();
            this.lblDosya = new System.Windows.Forms.Label();
            this.lblDurumDeger = new System.Windows.Forms.Label();
            this.lblDurum = new System.Windows.Forms.Label();
            this.lblGonderenDeger = new System.Windows.Forms.Label();
            this.lblGonderen = new System.Windows.Forms.Label();
            this.lblDirektorlukDeger = new System.Windows.Forms.Label();
            this.lblDirektorluk = new System.Windows.Forms.Label();
            this.lblDokumanTuruDeger = new System.Windows.Forms.Label();
            this.lblDokumanTuru = new System.Windows.Forms.Label();
            this.lblAciklamaDeger = new System.Windows.Forms.Label();
            this.lblAciklama = new System.Windows.Forms.Label();
            this.lblKonuDeger = new System.Windows.Forms.Label();
            this.lblKonu = new System.Windows.Forms.Label();
            this.lblDetayBaslik = new System.Windows.Forms.Label();
            this.dgvOnayBekleyenler = new System.Windows.Forms.DataGridView();
            this.pnlHeader.SuspendLayout();
            this.pnlContent.SuspendLayout();
            this.pnlAlt.SuspendLayout();
            this.pnlOrta.SuspendLayout();
            this.pnlDetay.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvOnayBekleyenler)).BeginInit();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.pnlHeader.Controls.Add(this.lblBaslik);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(1000, 60);
            this.pnlHeader.TabIndex = 0;
            this.lblBaslik.AutoSize = true;
            this.lblBaslik.Font = new System.Drawing.Font("Segoe UI Semibold", 14F, System.Drawing.FontStyle.Bold);
            this.lblBaslik.ForeColor = System.Drawing.Color.White;
            this.lblBaslik.Location = new System.Drawing.Point(20, 16);
            this.lblBaslik.Name = "lblBaslik";
            this.lblBaslik.Size = new System.Drawing.Size(132, 32);
            this.lblBaslik.TabIndex = 0;
            this.lblBaslik.Text = "Onay Ekranı";
            this.pnlContent.BackColor = System.Drawing.Color.WhiteSmoke;
            this.pnlContent.Controls.Add(this.pnlAlt);
            this.pnlContent.Controls.Add(this.pnlOrta);
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(0, 60);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Padding = new System.Windows.Forms.Padding(10);
            this.pnlContent.Size = new System.Drawing.Size(1000, 540);
            this.pnlContent.TabIndex = 1;
            this.pnlAlt.BackColor = System.Drawing.Color.White;
            this.pnlAlt.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlAlt.Controls.Add(this.lblRevizeAciklama);
            this.pnlAlt.Controls.Add(this.txtRevizeAciklama);
            this.pnlAlt.Controls.Add(this.btnRevizeTalep);
            this.pnlAlt.Controls.Add(this.btnReddet);
            this.pnlAlt.Controls.Add(this.btnOnayla);
            this.pnlAlt.Controls.Add(this.btnYenile);
            this.pnlAlt.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlAlt.Location = new System.Drawing.Point(10, 410);
            this.pnlAlt.Name = "pnlAlt";
            this.pnlAlt.Padding = new System.Windows.Forms.Padding(10);
            this.pnlAlt.Size = new System.Drawing.Size(980, 120);
            this.pnlAlt.TabIndex = 1;
            this.lblRevizeAciklama.AutoSize = true;
            this.lblRevizeAciklama.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblRevizeAciklama.Location = new System.Drawing.Point(13, 16);
            this.lblRevizeAciklama.Name = "lblRevizeAciklama";
            this.lblRevizeAciklama.Size = new System.Drawing.Size(182, 20);
            this.lblRevizeAciklama.TabIndex = 5;
            this.lblRevizeAciklama.Text = "Revize talep açıklaması (opsiyonel)";
            this.txtRevizeAciklama.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.txtRevizeAciklama.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtRevizeAciklama.Location = new System.Drawing.Point(16, 39);
            this.txtRevizeAciklama.Multiline = true;
            this.txtRevizeAciklama.Name = "txtRevizeAciklama";
            this.txtRevizeAciklama.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtRevizeAciklama.Size = new System.Drawing.Size(650, 65);
            this.txtRevizeAciklama.TabIndex = 0;
            this.btnRevizeTalep.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRevizeTalep.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRevizeTalep.Location = new System.Drawing.Point(680, 74);
            this.btnRevizeTalep.Name = "btnRevizeTalep";
            this.btnRevizeTalep.Size = new System.Drawing.Size(130, 30);
            this.btnRevizeTalep.TabIndex = 3;
            this.btnRevizeTalep.Text = "Revize Talep Et";
            this.btnRevizeTalep.UseVisualStyleBackColor = true;
            this.btnRevizeTalep.Click += new System.EventHandler(this.btnRevizeTalep_Click);
            this.btnReddet.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnReddet.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnReddet.Location = new System.Drawing.Point(816, 74);
            this.btnReddet.Name = "btnReddet";
            this.btnReddet.Size = new System.Drawing.Size(140, 30);
            this.btnReddet.TabIndex = 4;
            this.btnReddet.Text = "Reddet";
            this.btnReddet.UseVisualStyleBackColor = true;
            this.btnReddet.Click += new System.EventHandler(this.btnReddet_Click);
            this.btnOnayla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnOnayla.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.btnOnayla.Location = new System.Drawing.Point(816, 36);
            this.btnOnayla.Name = "btnOnayla";
            this.btnOnayla.Size = new System.Drawing.Size(140, 30);
            this.btnOnayla.TabIndex = 2;
            this.btnOnayla.Text = "Onayla";
            this.btnOnayla.UseVisualStyleBackColor = true;
            this.btnOnayla.Click += new System.EventHandler(this.btnOnayla_Click);
            this.btnYenile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnYenile.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnYenile.Location = new System.Drawing.Point(680, 36);
            this.btnYenile.Name = "btnYenile";
            this.btnYenile.Size = new System.Drawing.Size(130, 30);
            this.btnYenile.TabIndex = 1;
            this.btnYenile.Text = "Listeyi Yenile";
            this.btnYenile.UseVisualStyleBackColor = true;
            this.btnYenile.Click += new System.EventHandler(this.btnYenile_Click);
            this.pnlOrta.BackColor = System.Drawing.Color.Transparent;
            this.pnlOrta.Controls.Add(this.pnlDetay);
            this.pnlOrta.Controls.Add(this.dgvOnayBekleyenler);
            this.pnlOrta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlOrta.Location = new System.Drawing.Point(10, 10);
            this.pnlOrta.Name = "pnlOrta";
            this.pnlOrta.Padding = new System.Windows.Forms.Padding(0, 0, 5, 5);
            this.pnlOrta.Size = new System.Drawing.Size(980, 520);
            this.pnlOrta.TabIndex = 0;
            this.pnlDetay.BackColor = System.Drawing.Color.White;
            this.pnlDetay.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlDetay.Controls.Add(this.lblDosyaDeger);
            this.pnlDetay.Controls.Add(this.lblDosya);
            this.pnlDetay.Controls.Add(this.lblDurumDeger);
            this.pnlDetay.Controls.Add(this.lblDurum);
            this.pnlDetay.Controls.Add(this.lblGonderenDeger);
            this.pnlDetay.Controls.Add(this.lblGonderen);
            this.pnlDetay.Controls.Add(this.lblDirektorlukDeger);
            this.pnlDetay.Controls.Add(this.lblDirektorluk);
            this.pnlDetay.Controls.Add(this.lblDokumanTuruDeger);
            this.pnlDetay.Controls.Add(this.lblDokumanTuru);
            this.pnlDetay.Controls.Add(this.lblAciklamaDeger);
            this.pnlDetay.Controls.Add(this.lblAciklama);
            this.pnlDetay.Controls.Add(this.lblKonuDeger);
            this.pnlDetay.Controls.Add(this.lblKonu);
            this.pnlDetay.Controls.Add(this.lblDetayBaslik);
            this.pnlDetay.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlDetay.Location = new System.Drawing.Point(480, 0);
            this.pnlDetay.Name = "pnlDetay";
            this.pnlDetay.Padding = new System.Windows.Forms.Padding(10);
            this.pnlDetay.Size = new System.Drawing.Size(500, 515);
            this.pnlDetay.TabIndex = 1;
            this.lblDosyaDeger.AutoEllipsis = true;
            this.lblDosyaDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDosyaDeger.Location = new System.Drawing.Point(120, 260);
            this.lblDosyaDeger.Name = "lblDosyaDeger";
            this.lblDosyaDeger.Size = new System.Drawing.Size(360, 40);
            this.lblDosyaDeger.TabIndex = 14;
            this.lblDosyaDeger.Text = "-";
            this.lblDosya.AutoSize = true;
            this.lblDosya.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDosya.Location = new System.Drawing.Point(15, 260);
            this.lblDosya.Name = "lblDosya";
            this.lblDosya.Size = new System.Drawing.Size(51, 20);
            this.lblDosya.TabIndex = 13;
            this.lblDosya.Text = "Dosya:";
            this.lblDurumDeger.AutoSize = true;
            this.lblDurumDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDurumDeger.Location = new System.Drawing.Point(120, 230);
            this.lblDurumDeger.Name = "lblDurumDeger";
            this.lblDurumDeger.Size = new System.Drawing.Size(14, 20);
            this.lblDurumDeger.TabIndex = 12;
            this.lblDurumDeger.Text = "-";
            this.lblDurum.AutoSize = true;
            this.lblDurum.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDurum.Location = new System.Drawing.Point(15, 230);
            this.lblDurum.Name = "lblDurum";
            this.lblDurum.Size = new System.Drawing.Size(58, 20);
            this.lblDurum.TabIndex = 11;
            this.lblDurum.Text = "Durum:";
            this.lblGonderenDeger.AutoEllipsis = true;
            this.lblGonderenDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblGonderenDeger.Location = new System.Drawing.Point(120, 200);
            this.lblGonderenDeger.Name = "lblGonderenDeger";
            this.lblGonderenDeger.Size = new System.Drawing.Size(360, 20);
            this.lblGonderenDeger.TabIndex = 10;
            this.lblGonderenDeger.Text = "-";
            this.lblGonderen.AutoSize = true;
            this.lblGonderen.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblGonderen.Location = new System.Drawing.Point(15, 200);
            this.lblGonderen.Name = "lblGonderen";
            this.lblGonderen.Size = new System.Drawing.Size(78, 20);
            this.lblGonderen.TabIndex = 9;
            this.lblGonderen.Text = "Gönderen:";
            this.lblDirektorlukDeger.AutoEllipsis = true;
            this.lblDirektorlukDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDirektorlukDeger.Location = new System.Drawing.Point(120, 170);
            this.lblDirektorlukDeger.Name = "lblDirektorlukDeger";
            this.lblDirektorlukDeger.Size = new System.Drawing.Size(360, 20);
            this.lblDirektorlukDeger.TabIndex = 8;
            this.lblDirektorlukDeger.Text = "-";
            this.lblDirektorluk.AutoSize = true;
            this.lblDirektorluk.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDirektorluk.Location = new System.Drawing.Point(15, 170);
            this.lblDirektorluk.Name = "lblDirektorluk";
            this.lblDirektorluk.Size = new System.Drawing.Size(85, 20);
            this.lblDirektorluk.TabIndex = 7;
            this.lblDirektorluk.Text = "Direktörlük:";
            this.lblDokumanTuruDeger.AutoEllipsis = true;
            this.lblDokumanTuruDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDokumanTuruDeger.Location = new System.Drawing.Point(120, 140);
            this.lblDokumanTuruDeger.Name = "lblDokumanTuruDeger";
            this.lblDokumanTuruDeger.Size = new System.Drawing.Size(360, 20);
            this.lblDokumanTuruDeger.TabIndex = 6;
            this.lblDokumanTuruDeger.Text = "-";
            this.lblDetayBaslik.AutoSize = true;
            this.lblDetayBaslik.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            this.lblDetayBaslik.Location = new System.Drawing.Point(12, 15);
            this.lblDetayBaslik.Name = "lblDetayBaslik";
            this.lblDetayBaslik.Size = new System.Drawing.Size(96, 23);
            this.lblDetayBaslik.TabIndex = 0;
            this.lblDetayBaslik.Text = "Belge Detayı";
            this.lblKonu.AutoSize = true;
            this.lblKonu.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblKonu.Location = new System.Drawing.Point(15, 50);
            this.lblKonu.Name = "lblKonu";
            this.lblKonu.Size = new System.Drawing.Size(46, 20);
            this.lblKonu.TabIndex = 1;
            this.lblKonu.Text = "Konu:";
            this.lblKonuDeger.AutoEllipsis = true;
            this.lblKonuDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblKonuDeger.Location = new System.Drawing.Point(120, 50);
            this.lblKonuDeger.Name = "lblKonuDeger";
            this.lblKonuDeger.Size = new System.Drawing.Size(360, 20);
            this.lblKonuDeger.TabIndex = 2;
            this.lblKonuDeger.Text = "-";
            this.lblAciklama.AutoSize = true;
            this.lblAciklama.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblAciklama.Location = new System.Drawing.Point(15, 80);
            this.lblAciklama.Name = "lblAciklama";
            this.lblAciklama.Size = new System.Drawing.Size(71, 20);
            this.lblAciklama.TabIndex = 3;
            this.lblAciklama.Text = "Açıklama:";
            this.lblAciklamaDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblAciklamaDeger.Location = new System.Drawing.Point(120, 80);
            this.lblAciklamaDeger.Name = "lblAciklamaDeger";
            this.lblAciklamaDeger.Size = new System.Drawing.Size(360, 60);
            this.lblAciklamaDeger.TabIndex = 4;
            this.lblAciklamaDeger.Text = "-";
            this.lblDokumanTuru.AutoSize = true;
            this.lblDokumanTuru.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDokumanTuru.Location = new System.Drawing.Point(15, 150);
            this.lblDokumanTuru.Name = "lblDokumanTuru";
            this.lblDokumanTuru.Size = new System.Drawing.Size(104, 20);
            this.lblDokumanTuru.TabIndex = 5;
            this.lblDokumanTuru.Text = "Doküman türü:";
            this.lblDokumanTuruDeger.AutoEllipsis = true;
            this.lblDokumanTuruDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDokumanTuruDeger.Location = new System.Drawing.Point(120, 150);
            this.lblDokumanTuruDeger.Name = "lblDokumanTuruDeger";
            this.lblDokumanTuruDeger.Size = new System.Drawing.Size(360, 20);
            this.lblDokumanTuruDeger.TabIndex = 6;
            this.lblDokumanTuruDeger.Text = "-";
            this.lblDirektorluk.AutoSize = true;
            this.lblDirektorluk.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDirektorluk.Location = new System.Drawing.Point(15, 180);
            this.lblDirektorluk.Name = "lblDirektorluk";
            this.lblDirektorluk.Size = new System.Drawing.Size(85, 20);
            this.lblDirektorluk.TabIndex = 7;
            this.lblDirektorluk.Text = "Direktörlük:";
            this.lblDirektorlukDeger.AutoEllipsis = true;
            this.lblDirektorlukDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDirektorlukDeger.Location = new System.Drawing.Point(120, 180);
            this.lblDirektorlukDeger.Name = "lblDirektorlukDeger";
            this.lblDirektorlukDeger.Size = new System.Drawing.Size(360, 20);
            this.lblDirektorlukDeger.TabIndex = 8;
            this.lblDirektorlukDeger.Text = "-";
            this.lblGonderen.AutoSize = true;
            this.lblGonderen.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblGonderen.Location = new System.Drawing.Point(15, 210);
            this.lblGonderen.Name = "lblGonderen";
            this.lblGonderen.Size = new System.Drawing.Size(78, 20);
            this.lblGonderen.TabIndex = 9;
            this.lblGonderen.Text = "Gönderen:";
            this.lblGonderenDeger.AutoEllipsis = true;
            this.lblGonderenDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblGonderenDeger.Location = new System.Drawing.Point(120, 210);
            this.lblGonderenDeger.Name = "lblGonderenDeger";
            this.lblGonderenDeger.Size = new System.Drawing.Size(360, 20);
            this.lblGonderenDeger.TabIndex = 10;
            this.lblGonderenDeger.Text = "-";
            this.lblDurum.AutoSize = true;
            this.lblDurum.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDurum.Location = new System.Drawing.Point(15, 240);
            this.lblDurum.Name = "lblDurum";
            this.lblDurum.Size = new System.Drawing.Size(58, 20);
            this.lblDurum.TabIndex = 11;
            this.lblDurum.Text = "Durum:";
            this.lblDurumDeger.AutoSize = true;
            this.lblDurumDeger.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDurumDeger.Location = new System.Drawing.Point(120, 240);
            this.lblDurumDeger.Name = "lblDurumDeger";
            this.lblDurumDeger.Size = new System.Drawing.Size(14, 20);
            this.lblDurumDeger.TabIndex = 12;
            this.lblDurumDeger.Text = "-";
            this.lblDosya.AutoSize = true;
            this.lblDosya.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDosya.Location = new System.Drawing.Point(15, 270);
            this.lblDosya.Name = "lblDosya";
            this.lblDosya.Size = new System.Drawing.Size(51, 20);
            this.lblDosya.TabIndex = 13;
            this.lblDosya.Text = "Dosya:";
            this.lblDosyaDeger.AutoEllipsis = true;
            this.lblDosyaDeger.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblDosyaDeger.Location = new System.Drawing.Point(120, 270);
            this.lblDosyaDeger.Name = "lblDosyaDeger";
            this.lblDosyaDeger.Size = new System.Drawing.Size(360, 50);
            this.lblDosyaDeger.TabIndex = 14;
            this.lblDosyaDeger.Text = "-";
            this.dgvOnayBekleyenler.AllowUserToAddRows = false;
            this.dgvOnayBekleyenler.AllowUserToDeleteRows = false;
            this.dgvOnayBekleyenler.AllowUserToOrderColumns = true;
            this.dgvOnayBekleyenler.BackgroundColor = System.Drawing.Color.White;
            this.dgvOnayBekleyenler.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvOnayBekleyenler.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvOnayBekleyenler.Location = new System.Drawing.Point(0, 0);
            this.dgvOnayBekleyenler.MultiSelect = false;
            this.dgvOnayBekleyenler.Name = "dgvOnayBekleyenler";
            this.dgvOnayBekleyenler.ReadOnly = true;
            this.dgvOnayBekleyenler.RowHeadersVisible = false;
            this.dgvOnayBekleyenler.RowTemplate.Height = 24;
            this.dgvOnayBekleyenler.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvOnayBekleyenler.Size = new System.Drawing.Size(480, 515);
            this.dgvOnayBekleyenler.TabIndex = 0;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1000, 600);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.pnlHeader);
            this.MinimumSize = new System.Drawing.Size(1000, 600);
            this.Name = "FrmOnayEkrani";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Onay Ekranı";
            this.Load += new System.EventHandler(this.FrmOnayEkrani_Load);
            this.pnlHeader.ResumeLayout(false);
            this.pnlHeader.PerformLayout();
            this.pnlContent.ResumeLayout(false);
            this.pnlAlt.ResumeLayout(false);
            this.pnlAlt.PerformLayout();
            this.pnlOrta.ResumeLayout(false);
            this.pnlDetay.ResumeLayout(false);
            this.pnlDetay.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvOnayBekleyenler)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblBaslik;
        private System.Windows.Forms.Panel pnlContent;
        private System.Windows.Forms.Panel pnlAlt;
        private System.Windows.Forms.Label lblRevizeAciklama;
        private System.Windows.Forms.TextBox txtRevizeAciklama;
        private System.Windows.Forms.Button btnRevizeTalep;
        private System.Windows.Forms.Button btnReddet;
        private System.Windows.Forms.Button btnOnayla;
        private System.Windows.Forms.Button btnYenile;
        private System.Windows.Forms.Panel pnlOrta;
        private System.Windows.Forms.DataGridView dgvOnayBekleyenler;
        private System.Windows.Forms.Panel pnlDetay;
        private System.Windows.Forms.Label lblDetayBaslik;
        private System.Windows.Forms.Label lblKonuDeger;
        private System.Windows.Forms.Label lblKonu;
        private System.Windows.Forms.Label lblAciklamaDeger;
        private System.Windows.Forms.Label lblAciklama;
        private System.Windows.Forms.Label lblDokumanTuruDeger;
        private System.Windows.Forms.Label lblDokumanTuru;
        private System.Windows.Forms.Label lblDirektorlukDeger;
        private System.Windows.Forms.Label lblDirektorluk;
        private System.Windows.Forms.Label lblGonderenDeger;
        private System.Windows.Forms.Label lblGonderen;
        private System.Windows.Forms.Label lblDurumDeger;
        private System.Windows.Forms.Label lblDurum;
        private System.Windows.Forms.Label lblDosyaDeger;
        private System.Windows.Forms.Label lblDosya;
    }
}
